### ISSUE TITLE
This stuff just doesn't work at all

### ISSUE THREAD

**Issue by aemixdp** [atomjack/dubtrackapi#13]
I have latest phantomjs installed, when I run example code it just hangs.
No errors, no logging in. Maybe I'll try to debug this myself later.

**Comment by Plateam** [comment]
If you use cookie for logging in, make sure that connect.sid value is correct.

Check from issue  #6  [this answer](https://github.com/atomjack/dubtrackapi/issues/6#issuecomment-145277903).

Also, run it with node.js.

> node yourbothere.js

When you use browser to get your (new?) connect.sid, DO NOT log out.

If you use this, 'bot' computer to go to dubtrack with your personal account, i suggest you to create new user and use it when you want to connect to personal account. But do this only IF you use cookie. By that way, cookie(s) connect.sid doesn't change and bot can log-in.

_anything else that i should mention? hmmmmmmmmmmmm........_

**Comment by aemixdp** [comment]
@Plateam Thanks, but I'm not using cookie. I've created a new account and trying to login with username/password.

**Comment by ImGrumpy** [comment]
Ok, since so many people were having trouble with this, I decided to try it on a new machine.  Getting the prerequisites loaded is a bit of a challenge, so here's how I did it and got it working.

Environment Used: Windows 10 Home 64-bit
1. Download and install node.js (http://nodejs.org)
2. Download PhantomJS 2.0 (http://phantomjs.org)
3. Download and install git (https://git-for-windows.github.io) - recommend allowing Git from command prompt
4. Download and install python 2.7.10, not 3.x (http://python.org)
5. Download and Visual Studio Community, custom install, include Common Tools for C++ (https://www.visualstudio.com/en-us/downloads/download-visual-studio-vs.aspx)
6. Make a directory for your bot
7. From the PhantomJS zip, extract phantomjs.exe and put it in your bot directory.
8. Load a command prompt, change to the bot directory.

```
npm install phantomjs
npm install phantom (this is why python and visual studio are required)
npm install request
cd node_modules
git clone https://github.com/atomjack/dubtrackapi.git
```

Edit your sample code to include your login credentials, save as bot.js.
Change the require from "./dubtrackapi" to "dubtrackapi".

To run:
command prompt in bot directory

```
node bot.js
```

Your mileage may vary, but this should give you what you need to get it running under Windows.

**Comment by atomjack** [comment]
@aemxdp What OS are you running the bot on? And what exact version of phantomjs are you running?

If you'd like to provide more information I'll do what I can to help you. Start by pasting in the code to your bot's .js file (with the username & password x'd out of course). I assume you are running it with node, not phantomjs, right?

**Comment by aemixdp** [comment]
@ImGrumpy @atomjack 
Thanks for your suggestions, but I've decided that all this virtual browser stuff is too heavyweight and complicated for me, so I've reversed some requests in my 'Network' tab and switched to pure http now: https://github.com/aemxdp/dubmate/blob/master/server.js#L35
